add cors and use safe port
peterbe/fake-hydro pull request #1
Opened 2023-08-03 23:08 UTC by Ebonsignori

My browser didn't except `6666` by default, and running `npm run dev` locally didn't like hitting a port other than `3000` in the backend (cors), but adding the [cors](https://www.npmjs.com/package/cors) middleware library did the trick

2023-08-04 00:22 UTC, peterbe requested changes
What was wrong with `localhost:6666` that `localhost:8089` solved? :)

6666 sounds easier some how than 8089. Also, it's `PORT=8089 npm run dev` if you need it. 

Whatever the default is, it needs to match the README.

2023-08-04 14:46 UTC, peterbe commented
What was wrong with `6666`?

I know that `:5000` is used, on the mac by some app in the Control Center. That surprised a lot of local developers. For example, Flask uses :5000 as their default. 

If you can suggest a number that doesn't cause annoying conflicts for mac and linux users, let's change the default and change the README.

2023-08-04 14:46 UTC, peterbe commented
By the way, I threw in `cors` here: https://github.com/peterbe/fake-hydro/commit/fbc5c9797cb2c296843f13323cf27786e7efb303

2023-08-04 15:05 UTC, peterbe commented
I too now see the problem with :6666 and read some blog posts and Stack overflow about it. 
See https://github.com/peterbe/fake-hydro/pull/3

2023-08-04 15:05 UTC, closed without merging

2024-05-19 16:21 UTC, thannawat152005 commented
peterbe/fake-hydro:main.
No new commits to fetch. Enjoy your day!

2024-05-19 16:21 UTC, thannawat152005 commented
``

2024-05-19 16:22 UTC, thannawat152005 commented on package.json
Ebonsignori:main

2024-05-19 16:22 UTC, thannawat152005 reviewed
src/index.js

2024-05-19 16:22 UTC, thannawat152005 commented on package.json
src/index.js

2024-05-19 16:23 UTC, thannawat152005 commented
src/index.js